env: "local"
grpc_server:
  host: "localhost"
  port: "50057"
banking_db:
  dsn: "host=banking-db user=postgres password=admin dbname=shvark_banking_service port=5432 sslmode=disable"
log_config:
  log_level: "debug"
  log_format: "json"
  log_output: "stdout"